### ISSUE TITLE
--iprange net not working

### ISSUE THREAD

**Issue by benbrummer** [gudesystems/upload.py#1]
Formerly we used
```
python3 ./upload.py --onlineupdate
```
This fails now as "gbl=search" was disabled in 988e08939bf8dd165feb539c0d5bcb34564b44f7

Therefore i switched to

```
python3 ./upload.py --onlineupdate --iprange 10.78.0.0/23
```

Which tries to update 10.78.0.0, which is of course no valid Address

```
+ python3 ./upload.py --onlineupdate --iprange 10.78.0.0/23
trying 512 devices
trying 10.78.0.0...
Traceback (most recent call last):
  File "./upload.py", line 54, in <module>
    if not gbl.check_mac(str(ip)):
  File "/home/agent/jenkins/workspace/gudeUpdate/gude/gblib.py", line 153, in check_mac
    data = Gblib.send_gbl(ip_addr, Gblib.GBL_NETCONF, self.default_timeout)
  File "/home/agent/jenkins/workspace/gudeUpdate/gude/gblib.py", line 36, in send_gbl
    s.sendto(payload + bytes([chksum]), (ip_addr, 50123))
PermissionError: [Errno 13] Permission denied
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by benbrummer** [comment]
Is there a commandline switch for "gbl=search"

**Comment by benbrummer** [comment]
I now use "sed" to enable gbl=search
```
sed -i "s/#gbl=search/gbl=search/g" "./upload.ini"
python3 -m venv venv
source ./venv/bin/activate
pip3 install requests
python3 ./upload.py --onlineupdate
```

**Comment by gudesystems** [comment]
> Is there a commandline switch for "gbl=search"

Hi,
you can set up your own ini, e.g. named 'custom1.ini', and select all options by
  ./upload.py -u custom1.ini

This way, new defaults settings in the github controlled upload.ini won't clash with your custom1.ini setup, and you can manage multiple sites using different INI settings.

**Comment by gudesystems** [comment]
> Is there a commandline switch for "gbl=search"

yes:

./upload.py --iprange search
Searching devices by GBL UDP broadcast...
trying 0 devices

**Comment by gudesystems** [comment]
> Formerly we used
> 
> ```
> python3 ./upload.py --onlineupdate
> ```
> 
> This fails now as "gbl=search" was disabled in [988e089](https://github.com/gudesystems/upload.py/commit/988e08939bf8dd165feb539c0d5bcb34564b44f7)
> 
> Therefore i switched to
> 
> ```
> python3 ./upload.py --onlineupdate --iprange 10.78.0.0/23
> ```
> 
> Which tries to update 10.78.0.0, which is of course no valid Address
> 
> ```
> + python3 ./upload.py --onlineupdate --iprange 10.78.0.0/23
> trying 512 devices
> trying 10.78.0.0...
> Traceback (most recent call last):
>   File "./upload.py", line 54, in <module>
>     if not gbl.check_mac(str(ip)):
>   File "/home/agent/jenkins/workspace/gudeUpdate/gude/gblib.py", line 153, in check_mac
>     data = Gblib.send_gbl(ip_addr, Gblib.GBL_NETCONF, self.default_timeout)
>   File "/home/agent/jenkins/workspace/gudeUpdate/gude/gblib.py", line 36, in send_gbl
>     s.sendto(payload + bytes([chksum]), (ip_addr, 50123))
> PermissionError: [Errno 13] Permission denied
> Build step 'Execute shell' marked build as failure
> Finished: FAILURE
> ```

Thanks, this should be fixed by the latest commit.
