### ISSUE TITLE
Upload fails for R2 Firmware devices

### ISSUE THREAD

**Issue by benbrummer** [gudesystems/upload.py#2]
`Expert Power Control 8031-3 (80xxR2, 00_19_32_01_4d_33) at X.X.X.X
        running Fimware v1.2.3-R2
downloading https://files.gude-systems.com/fw/gude/firmware-epc8031-r2.json
        updateing to Fimware v1.2.4
uploading firmware-epc8031_v1.2.4.bin, please wait...
uploading 1200604 bytes...
upload progress 2.15% 25832/1200604
upload progress 6.50% 78056/1200604
upload progress 10.85% 130280/1200604
upload progress 15.22% 182760/1200604
upload progress 19.51% 234216/1200604
upload progress 23.88% 286696/1200604
upload progress 28.23% 338920/1200604
upload progress 32.58% 391144/1200604
upload progress 36.93% 443368/1200604
upload progress 40.92% 491240/1200604
upload progress 45.27% 543464/1200604
upload progress 49.64% 595944/1200604
upload progress 53.99% 648168/1200604
upload progress 58.34% 700392/1200604
upload progress 62.71% 752872/1200604
upload progress 67.04% 804840/1200604
upload progress 71.39% 857064/1200604
upload progress 76.08% 913384/1200604
upload progress 80.45% 965864/1200604
upload progress 84.78% 1017832/1200604
upload progress 89.13% 1070056/1200604
upload progress 93.48% 1122280/1200604
upload progress 97.83% 1174504/1200604
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/gude/upload.py/gude/deployDev.py", line 41, in threadedUpload
    self.uploadFile(self.fw, self.CGI_UPLOAD_TYPE_FIRMWARE, timeout=300.0)
  File "/root/gude/upload.py/gude/httpDevice.py", line 820, in uploadFile
    raise ValueError("http request error {0}".format(r.status_code))
ValueError: http request error 415
upload progress 100.00% 1200604/1200604
upload progress 100.00% 1200604/1200604
upload progress 100.00% 1200604/1200604
upload progress 100.00% 1200604/1200604
upload progress 100.00% 1200604/1200604
`

**Comment by fabian-n-gude-systems** [comment]
Thank you for your report.
We found a small typo in our `version.ini` that seemed to cause your issue. 
Just pull the latest commit and you should be able to update your hardware.

Please let us know if you have any other problems.

**Comment by benbrummer** [comment]
Hi, upload is still not properly handled. After pulling the latest commit:
It updates the Firmware even if it is already on the latest version.
```
Expert Power Control 8031-3 (80xxR2, 00_19_32_01_4d_33) at x.x.x.x
        running Fimware v1.3.0-R2
downloading https://files.gude-systems.com/fw/gude/firmware-epc8031-r2.json
        updateing to Fimware v1.3.0
uploading firmware-epc8031-r2_v1.3.0.bin, please wait...
uploading 1210582 bytes...
...
```

**Comment by fabian-n-gude-systems** [comment]
> Hi, upload is still not properly handled. After pulling the latest commit: It updates the Firmware even if it is already on the latest version.
> 
> ```
> Expert Power Control 8031-3 (80xxR2, 00_19_32_01_4d_33) at x.x.x.x
>         running Fimware v1.3.0-R2
> downloading https://files.gude-systems.com/fw/gude/firmware-epc8031-r2.json
>         updateing to Fimware v1.3.0
> uploading firmware-epc8031-r2_v1.3.0.bin, please wait...
> uploading 1210582 bytes...
> ...
> ```

Please see #5
